name: scr
on: [push, pull_request]
env:
  url: ${{ secrets.url }}
  src: ${{ secrets.src }}
jobs:
  build:
    runs-on: ubuntu-20.04
    container: dazz111/yfd:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Add your build and test steps here
      
      - name: Create ZIP file
        run: |
          mkdir output
          apt install libcurl4-openssl-dev libssl-dev  -y
          wget -q $src
          wget -q $url
          lscpu
          # while read line; do python3 tscr.py "$line" > /dev/null; echo "$line" | tee -a tsite-map-1.txt; done < tsite-map.txt
          bash run.sh
          
          # add commands to populate the "output" directory with files and folders
          zip -r output.zip output
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.zip
      - name: Upload artifact 2
        uses: actions/upload-artifact@v2
        with:
          name: tsite-map
          path: tsite-map-1.txt

